import {
    SiKubernetes, SiArgo, SiPrometheus, SiGrafana, SiTerraform, SiHelm, SiIstio, SiDocker,
    SiVault, SiOpentelemetry, SiEnvoyproxy, SiNginx, SiConsul,
    SiRedis, SiPostgresql, SiMongodb, SiApachekafka, SiElasticsearch,
    SiGithubactions, SiGitlab, SiJenkins, SiKong, SiCloudflare,
    SiRancher, SiPodman, SiDatadog, SiSentry, SiAnsible, SiPulumi,
    SiGithub, SiGithubcopilot, SiOpenai, SiHuggingface, SiAnthropic, SiGooglegemini,
    SiNewrelic, SiDynatrace, SiSplunk, SiJaeger, SiFluentd, SiElastic, SiKibana, SiLogstash,
    SiStripe, SiPaypal, SiApplepay, SiGooglepay, SiShopify, SiSlack, SiDiscord, SiTwilio, SiSendgrid
} from 'react-icons/si';
import {
    ArchitectureServiceAmazonEC2,
    ArchitectureServiceAWSLambda,
    ArchitectureServiceAmazonDynamoDB,
    ArchitectureServiceAmazonRDS,
    ArchitectureServiceAmazonSimpleStorageService,
    ArchitectureServiceAmazonEFS,
    ArchitectureServiceAmazonVirtualPrivateCloud,
    ArchitectureServiceAmazonRoute53,
    ArchitectureServiceAmazonSimpleQueueService,
    ArchitectureServiceAmazonSimpleNotificationService,
    CategorySecurityIdentityCompliance,
    ArchitectureServiceAmazonCloudWatch,
    ArchitectureServiceAmazonElasticKubernetesService,
    ArchitectureServiceAmazonElasticContainerService,
    ArchitectureServiceAWSAmplify,
    ArchitectureServiceAmazonAPIGateway,
    ResourceElasticLoadBalancingApplicationLoadBalancer,
    ResourceAmazonVPCNATGateway,
    ResourceAmazonVPCInternetGateway,
    ArchitectureGroupPrivatesubnet,
    ArchitectureServiceAmazonCloudFront,
    ArchitectureServiceAmazonElastiCache,
    ArchitectureServiceAmazonKinesis,
    CategoryCompute,
    CategoryDatabase,
    CategoryStorage,
    CategoryNetworkingContentDelivery,
    ArchitectureServiceAWSGlue,
    ArchitectureServiceAWSStepFunctions,
    ArchitectureServiceAmazonEventBridge,
    ArchitectureServiceAmazonAthena,
    ArchitectureServiceAmazonEMR,
    ArchitectureServiceAWSDirectConnect,
    ArchitectureServiceAWSClientVPN,
    ArchitectureServiceAWSSitetoSiteVPN,
    ArchitectureServiceAmazonRedshift,
    ArchitectureServiceAmazonQuickSight,
    ArchitectureServiceAmazonOpenSearchService,
    ArchitectureServiceAmazonManagedStreamingforApacheKafka,
    ArchitectureServiceAWSBatch,
    ArchitectureServiceAWSElasticBeanstalk,
    ArchitectureServiceAmazonElasticContainerRegistry,
    ArchitectureServiceAWSAppSync,
    ArchitectureServiceAmazonMQ,
    // AI & Machine Learning
    ArchitectureServiceAmazonBedrock,
    ArchitectureServiceAmazonSageMaker,
    ArchitectureServiceAmazonRekognition,
    ArchitectureServiceAmazonComprehend,
    ArchitectureServiceAmazonTextract,
    ArchitectureServiceAmazonTranslate,
    ArchitectureServiceAmazonTranscribe,
    ArchitectureServiceAmazonPolly,
    ArchitectureServiceAmazonLex,
    ArchitectureServiceAmazonPersonalize,
    ArchitectureServiceAmazonForecast,
    ArchitectureServiceAmazonKendra,
    CategoryArtificialIntelligence,
    // Developer Tools
    ArchitectureServiceAWSCodePipeline,
    ArchitectureServiceAWSCodeBuild,
    ArchitectureServiceAWSCodeDeploy,
    ArchitectureServiceAWSCodeCommit,
    ArchitectureServiceAWSCodeArtifact,
    ArchitectureServiceAWSCloud9,
    ArchitectureServiceAWSXRay,
    CategoryDeveloperTools,
    // Security
    ArchitectureServiceAmazonCognito,
    ArchitectureServiceAWSSecretsManager,
    ArchitectureServiceAmazonGuardDuty,
    ArchitectureServiceAmazonInspector,
    ArchitectureServiceAmazonMacie,
    ArchitectureServiceAWSSecurityHub,
    ArchitectureServiceAWSCertificateManager,
    ArchitectureServiceAWSCloudHSM,
    ArchitectureServiceAWSShield,
    ArchitectureServiceAWSKeyManagementService,
    ArchitectureServiceAWSWAF,
    // Database
    ArchitectureServiceAmazonNeptune,
    ArchitectureServiceAmazonDocumentDB,
    ArchitectureServiceAmazonTimestream,
    ArchitectureServiceAmazonKeyspaces,
    ArchitectureServiceAmazonMemoryDB,
    ArchitectureServiceAmazonQuantumLedgerDatabase,
    // Storage
    ArchitectureServiceAmazonFSx,
    ArchitectureServiceAWSBackup,
    ArchitectureServiceAWSStorageGateway,
    ArchitectureServiceAmazonSimpleStorageServiceGlacier,
    ArchitectureServiceAmazonElasticBlockStore,
    // Compute
    ArchitectureServiceAWSFargate,
    ArchitectureServiceAmazonLightsail,
    ArchitectureServiceAWSAppRunner,
    // Containers
    ArchitectureServiceAmazonEKSAnywhere,
    ArchitectureServiceAmazonECSAnywhere,
    CategoryContainers,
    // Management & Governance
    ArchitectureServiceAWSSystemsManager,
    ArchitectureServiceAWSConfig,
    ArchitectureServiceAWSCloudTrail,
    ArchitectureServiceAWSOrganizations,
    ArchitectureServiceAWSControlTower,
    ArchitectureServiceAWSServiceCatalog,
    ArchitectureServiceAWSTrustedAdvisor,
    ArchitectureServiceAWSCloudFormation,
    CategoryManagementGovernance,
    // Migration & Transfer
    ArchitectureServiceAWSDatabaseMigrationService,
    ArchitectureServiceAWSDataSync,
    ArchitectureServiceAWSTransferFamily,
    ArchitectureServiceAWSMigrationHub,
    ArchitectureServiceAWSTransitGateway,
    CategoryMigrationModernization,
    CategoryApplicationIntegration,
    CategoryAnalytics,
} from 'aws-react-icons';
import { Cloud, Box, LucideIcon, User, Smartphone, Globe, Monitor, Laptop, Cpu, Layers, Webhook, ShoppingCart } from 'lucide-react';

// Define a type that can be either an AWS Icon component or a Lucide Icon
type IconComponent = React.ComponentType<any> | LucideIcon;

export const getAwsIcon = (service: string, type: string): IconComponent => {
    // Normalize input
    const normalizedService = service?.toLowerCase().replace(/\s+/g, '') || '';
    const normalizedType = type?.toLowerCase() || '';

    // 1. Direct Service Mapping
    const serviceMap: Record<string, React.ComponentType<any>> = {
        'ec2': ArchitectureServiceAmazonEC2,
        'lambda': ArchitectureServiceAWSLambda,
        's3': ArchitectureServiceAmazonSimpleStorageService,
        'dynamodb': ArchitectureServiceAmazonDynamoDB,
        'rds': ArchitectureServiceAmazonRDS,
        'vpc': ArchitectureServiceAmazonVirtualPrivateCloud,
        'sqs': ArchitectureServiceAmazonSimpleQueueService,
        'sns': ArchitectureServiceAmazonSimpleNotificationService,
        'iam': CategorySecurityIdentityCompliance,
        'cloudwatch': ArchitectureServiceAmazonCloudWatch,
        'eks': ArchitectureServiceAmazonElasticKubernetesService,
        'ecs': ArchitectureServiceAmazonElasticContainerService,
        'efs': ArchitectureServiceAmazonEFS,
        'route53': ArchitectureServiceAmazonRoute53,
        'amplify': ArchitectureServiceAWSAmplify,
        'apigateway': ArchitectureServiceAmazonAPIGateway,
        'directconnect': ArchitectureServiceAWSDirectConnect,
        'clientvpn': ArchitectureServiceAWSClientVPN,
        'sitetositevpn': ArchitectureServiceAWSSitetoSiteVPN,
        'vpn': ArchitectureServiceAWSClientVPN,
        'transitgateway': ArchitectureServiceAWSTransitGateway,
        'elb': ResourceElasticLoadBalancingApplicationLoadBalancer,
        'alb': ResourceElasticLoadBalancingApplicationLoadBalancer,
        'applicationloadbalancer': ResourceElasticLoadBalancingApplicationLoadBalancer,
        'natgateway': ResourceAmazonVPCNATGateway,
        'internetgateway': ResourceAmazonVPCInternetGateway,
        'privatesubnet': ArchitectureGroupPrivatesubnet,
        'elasticloadbalancing': ResourceElasticLoadBalancingApplicationLoadBalancer,
        'cloudfront': ArchitectureServiceAmazonCloudFront,
        'elasticache': ArchitectureServiceAmazonElastiCache,
        'kinesis': ArchitectureServiceAmazonKinesis,
        'glue': ArchitectureServiceAWSGlue,
        'stepfunctions': ArchitectureServiceAWSStepFunctions,
        'eventbridge': ArchitectureServiceAmazonEventBridge,
        'athena': ArchitectureServiceAmazonAthena,
        'emr': ArchitectureServiceAmazonEMR,
        'redshift': ArchitectureServiceAmazonRedshift,
        'quicksight': ArchitectureServiceAmazonQuickSight,
        'opensearch': ArchitectureServiceAmazonOpenSearchService,
        'msk': ArchitectureServiceAmazonManagedStreamingforApacheKafka,
        'batch': ArchitectureServiceAWSBatch,
        'elasticbeanstalk': ArchitectureServiceAWSElasticBeanstalk,
        'ecr': ArchitectureServiceAmazonElasticContainerRegistry,
        'appsync': ArchitectureServiceAWSAppSync,
        'mq': ArchitectureServiceAmazonMQ,
        // AI & Machine Learning
        'bedrock': ArchitectureServiceAmazonBedrock,
        'sagemaker': ArchitectureServiceAmazonSageMaker,
        'rekognition': ArchitectureServiceAmazonRekognition,
        'comprehend': ArchitectureServiceAmazonComprehend,
        'textract': ArchitectureServiceAmazonTextract,
        'translate': ArchitectureServiceAmazonTranslate,
        'transcribe': ArchitectureServiceAmazonTranscribe,
        'polly': ArchitectureServiceAmazonPolly,
        'lex': ArchitectureServiceAmazonLex,
        'personalize': ArchitectureServiceAmazonPersonalize,
        'forecast': ArchitectureServiceAmazonForecast,
        'kendra': ArchitectureServiceAmazonKendra,
        // Developer Tools
        'codepipeline': ArchitectureServiceAWSCodePipeline,
        'codebuild': ArchitectureServiceAWSCodeBuild,
        'codecommit': ArchitectureServiceAWSCodeCommit,
        'codedeploy': ArchitectureServiceAWSCodeDeploy,
        'codeartifact': ArchitectureServiceAWSCodeArtifact,
        'cloud9': ArchitectureServiceAWSCloud9,
        'xray': ArchitectureServiceAWSXRay,
        'x-ray': ArchitectureServiceAWSXRay,
        // Security
        'cognito': ArchitectureServiceAmazonCognito,
        'secretsmanager': ArchitectureServiceAWSSecretsManager,
        'guardduty': ArchitectureServiceAmazonGuardDuty,
        'inspector': ArchitectureServiceAmazonInspector,
        'macie': ArchitectureServiceAmazonMacie,
        'securityhub': ArchitectureServiceAWSSecurityHub,
        'certificatemanager': ArchitectureServiceAWSCertificateManager,
        'acm': ArchitectureServiceAWSCertificateManager,
        'cloudhsm': ArchitectureServiceAWSCloudHSM,
        'shield': ArchitectureServiceAWSShield,
        'kms': ArchitectureServiceAWSKeyManagementService,
        'waf': ArchitectureServiceAWSWAF,
        // Database
        'neptune': ArchitectureServiceAmazonNeptune,
        'documentdb': ArchitectureServiceAmazonDocumentDB,
        'timestream': ArchitectureServiceAmazonTimestream,
        'keyspaces': ArchitectureServiceAmazonKeyspaces,
        'memorydb': ArchitectureServiceAmazonMemoryDB,
        'qldb': ArchitectureServiceAmazonQuantumLedgerDatabase,
        // Storage
        'fsx': ArchitectureServiceAmazonFSx,
        'backup': ArchitectureServiceAWSBackup,
        'storagegateway': ArchitectureServiceAWSStorageGateway,
        's3-glacier': ArchitectureServiceAmazonSimpleStorageServiceGlacier,
        'glacier': ArchitectureServiceAmazonSimpleStorageServiceGlacier,
        'ebs': ArchitectureServiceAmazonElasticBlockStore,
        // Compute
        'fargate': ArchitectureServiceAWSFargate,
        'lightsail': ArchitectureServiceAmazonLightsail,
        'apprunner': ArchitectureServiceAWSAppRunner,
        // Containers
        'eksanywhere': ArchitectureServiceAmazonEKSAnywhere,
        'ecsanywhere': ArchitectureServiceAmazonECSAnywhere,
        // Management & Governance
        'systemsmanager': ArchitectureServiceAWSSystemsManager,
        'ssm': ArchitectureServiceAWSSystemsManager,
        'config': ArchitectureServiceAWSConfig,
        'cloudtrail': ArchitectureServiceAWSCloudTrail,
        'organizations': ArchitectureServiceAWSOrganizations,
        'controltower': ArchitectureServiceAWSControlTower,
        'servicecatalog': ArchitectureServiceAWSServiceCatalog,
        'trustedadvisor': ArchitectureServiceAWSTrustedAdvisor,
        'cloudformation': ArchitectureServiceAWSCloudFormation,
        // Migration & Transfer
        'dms': ArchitectureServiceAWSDatabaseMigrationService,
        'datasync': ArchitectureServiceAWSDataSync,
        'transferfamily': ArchitectureServiceAWSTransferFamily,
        'migrationhub': ArchitectureServiceAWSMigrationHub,
        // Client / Generic Mappings
        'user': User,
        'browser': Globe,
        'mobile': Smartphone,
        'client': Monitor,
        'iot-device': Cpu,
        // GitHub Services
        'github': SiGithub,
        'githubcopilot': SiGithubcopilot,
        'copilot': SiGithubcopilot,
        'codespaces': SiGithub, // Fallback as no specific icon exists
        // Alternative AI
        'openai': SiOpenai,
        'huggingface': SiHuggingface,
        'anthropic': SiAnthropic,
        'gemini': SiGooglegemini,
        'googlegemini': SiGooglegemini,
        'midjourney': Box, // Adding mapping even if fallback is needed depending on library version
        // Cloud Native
        'kubernetes': SiKubernetes,
        'k8s': SiKubernetes,
        'argocd': SiArgo,
        'argo': SiArgo,
        'crossplane': Layers,
        'prometheus': SiPrometheus,
        'grafana': SiGrafana,
        'terraform': SiTerraform,
        'helm': SiHelm,
        'istio': SiIstio,
        'docker': SiDocker,
        'vault': SiVault,
        'opentelemetry': SiOpentelemetry,
        'envoy': SiEnvoyproxy,
        'nginx': SiNginx,
        'consul': SiConsul,
        // Database & integration
        'redis': SiRedis,
        'postgresql': SiPostgresql,
        'postgres': SiPostgresql,
        'mongodb': SiMongodb,
        'mongo': SiMongodb,
        'kafka': SiApachekafka,
        'elasticsearch': SiElasticsearch,
        // CI/CD & DevOps
        'githubactions': SiGithubactions,
        'gitlab': SiGitlab,
        'jenkins': SiJenkins,
        'ansible': SiAnsible,
        'pulumi': SiPulumi,
        // API Gateways & Networking
        'kong': SiKong,
        'cloudflare': SiCloudflare,
        // Containers (Alternative)
        'rancher': SiRancher,
        'podman': SiPodman,
        // Observability
        'datadog': SiDatadog,
        'sentry': SiSentry,
        'newrelic': SiNewrelic,
        'dynatrace': SiDynatrace,
        'splunk': SiSplunk,
        'jaeger': SiJaeger,
        'fluentd': SiFluentd,
        'elastic': SiElastic,
        'kibana': SiKibana,
        'logstash': SiLogstash,
        // Integrations & Payments
        'stripe': SiStripe,
        'paypal': SiPaypal,
        'applepay': SiApplepay,
        'googlepay': SiGooglepay,
        'shopify': SiShopify,
        'checkout': ShoppingCart,
        'webhook': Webhook,
        'slack': SiSlack,
        'discord': SiDiscord,
        'twilio': SiTwilio,
        'sendgrid': SiSendgrid,
    };

    // Check for exact match or partial match in service name
    if (serviceMap[normalizedService]) {
        return serviceMap[normalizedService];
    }

    // Try to find a key that is contained within the service string
    const foundServiceKey = Object.keys(serviceMap).find(key => normalizedService.includes(key));
    if (foundServiceKey) {
        return serviceMap[foundServiceKey];
    }

    // 2. Type Mapping (Fallback)
    const typeMap: Record<string, React.ComponentType<any>> = {
        'aws-compute': CategoryCompute,
        'aws-database': CategoryDatabase,
        'aws-storage': CategoryStorage,
        'aws-network': CategoryNetworkingContentDelivery,
        'aws-ai': CategoryArtificialIntelligence,
        'aws-ml': CategoryArtificialIntelligence,
        'aws-devtools': CategoryDeveloperTools,
        'aws-security': CategorySecurityIdentityCompliance,
        'aws-containers': CategoryContainers,
        'aws-management': CategoryManagementGovernance,
        'aws-migration': CategoryMigrationModernization,
        'aws-integration': CategoryApplicationIntegration,
        'aws-analytics': CategoryAnalytics,
        'compute': CategoryCompute,
        'database': CategoryDatabase,
        'storage': CategoryStorage,
        'network': CategoryNetworkingContentDelivery,
        'ai': CategoryArtificialIntelligence,
        'ml': CategoryArtificialIntelligence,
        'devtools': CategoryDeveloperTools,
        'security': CategorySecurityIdentityCompliance,
        'containers': CategoryContainers,
        'management': CategoryManagementGovernance,
        'migration': CategoryMigrationModernization,
        'integration': CategoryApplicationIntegration,
        'analytics': CategoryAnalytics,
    };

    if (typeMap[normalizedType]) {
        return typeMap[normalizedType];
    }

    // 3. Last Resort Fallback
    return Cpu;
};
