app = "y-webrtc-signaling"
primary_region = "gru" # Choose the region closest to you

[http_service]
  internal_port = 4444
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[vm]
  memory = "256mb"
  cpu_kind = "shared"
  cpus = 1

[env]
  PORT = "4444"
