import type { AppNode, AppEdge } from "@/lib/store";
import type { TableColumn } from "@/components/diagram/TableNode";

function sanitizeName(name: string): string {
  return name.replace(/\s+/g, "_").replace(/[^\w]/g, "");
}

function toSqlType(type: string): string {
  const upper = type.toUpperCase();
  // Already valid SQL types — pass through
  if (/^(INT|INTEGER|BIGINT|SMALLINT|TINYINT|SERIAL|BIGSERIAL)$/.test(upper))
    return upper;
  if (/^(VARCHAR|CHAR|TEXT|NVARCHAR|NCHAR)/.test(upper)) return type;
  if (/^(FLOAT|DOUBLE|DECIMAL|NUMERIC|REAL)/.test(upper)) return type;
  if (/^(BOOLEAN|BOOL)$/.test(upper)) return "BOOLEAN";
  if (/^(DATE|TIME|DATETIME|TIMESTAMP)/.test(upper)) return upper;
  if (/^(JSON|JSONB|UUID|BLOB|BYTEA)$/.test(upper)) return upper;
  // Unknown types — wrap as VARCHAR(255) with original as comment
  return `VARCHAR(255) /* ${type} */`;
}

export function exportSqlDdl(
  nodes: AppNode[],
  edges: AppEdge[],
  diagramName: string,
): void {
  const tableNodes = nodes.filter((n) => n.type === "table");

  const lines: string[] = [
    `-- SQL DDL generated by OpenArchFlow`,
    `-- Diagram: ${diagramName}`,
    `-- Generated at: ${new Date().toISOString()}`,
    "",
  ];

  if (tableNodes.length === 0) {
    lines.push("-- No table nodes found in this diagram.");
    lines.push("-- Add Table nodes and define columns to generate DDL.");
    triggerDownload(lines.join("\n"), diagramName);
    return;
  }

  // Build a map of tableId -> tableName for FK resolution
  const tableNameById = new Map<string, string>();
  tableNodes.forEach((n) => {
    tableNameById.set(n.id, sanitizeName(n.data.label || "table"));
  });

  // Build FK map: edge from table A column → table B's PK column name
  // Edges between table nodes represent FK relationships (source → target)
  const fkEdges = edges.filter(
    (e) => tableNameById.has(e.source) && tableNameById.has(e.target),
  );

  // For each table: which columns reference which other table's PK
  // Map: sourceTableId -> Array<{ sourceColName, targetTableId, targetColName }>
  const fkMap = new Map<
    string,
    { sourceColName: string; targetTableId: string; targetColName: string }[]
  >();

  fkEdges.forEach((edge) => {
    const targetNode = tableNodes.find((n) => n.id === edge.target);
    if (!targetNode) return;
    const targetCols: TableColumn[] = targetNode.data.metadata?.columns ?? [];
    const targetPk = targetCols.find((c) => c.isPrimaryKey);
    if (!targetPk) return;

    // Use edge label or data to find the source column; fall back to matching FK-marked col
    const sourceNode = tableNodes.find((n) => n.id === edge.source);
    if (!sourceNode) return;
    const sourceCols: TableColumn[] = sourceNode.data.metadata?.columns ?? [];
    const sourceCol = sourceCols.find((c) => c.isForeignKey) ?? sourceCols[0];
    if (!sourceCol) return;

    if (!fkMap.has(edge.source)) fkMap.set(edge.source, []);
    fkMap.get(edge.source)!.push({
      sourceColName: sourceCol.name,
      targetTableId: edge.target,
      targetColName: targetPk.name,
    });
  });

  // Generate CREATE TABLE for each table node
  tableNodes.forEach((node) => {
    const tableName = tableNameById.get(node.id) || "table";
    const columns: TableColumn[] = node.data.metadata?.columns ?? [];
    const fks = fkMap.get(node.id) ?? [];

    lines.push(`CREATE TABLE ${tableName} (`);

    const colDefs: string[] = [];

    columns.forEach((col) => {
      const colName = sanitizeName(col.name) || "column";
      const sqlType = toSqlType(col.type || "VARCHAR(255)");
      const notNull =
        col.isPrimaryKey || col.nullable === false ? " NOT NULL" : "";
      colDefs.push(`    ${colName} ${sqlType}${notNull}`);
    });

    // Primary key constraint
    const pkCols = columns
      .filter((c) => c.isPrimaryKey)
      .map((c) => sanitizeName(c.name));
    if (pkCols.length > 0) {
      colDefs.push(`    PRIMARY KEY (${pkCols.join(", ")})`);
    }

    // Foreign key constraints
    fks.forEach((fk) => {
      const refTable = tableNameById.get(fk.targetTableId) || "other_table";
      const srcCol = sanitizeName(fk.sourceColName);
      const refCol = sanitizeName(fk.targetColName);
      colDefs.push(
        `    FOREIGN KEY (${srcCol}) REFERENCES ${refTable}(${refCol})`,
      );
    });

    lines.push(colDefs.join(",\n"));
    lines.push(");");
    lines.push("");
  });

  triggerDownload(lines.join("\n"), diagramName);
}

function triggerDownload(content: string, diagramName: string): void {
  const blob = new Blob([content], { type: "text/sql" });
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = `${sanitizeName(diagramName) || "diagram"}.sql`;
  link.click();
  URL.revokeObjectURL(url);
}
