import React from 'react';
import { IconComponent } from '../types';
import { Cpu } from 'lucide-react';
import {
    ArchitectureServiceAmazonEC2,
    ArchitectureServiceAWSLambda,
    ArchitectureServiceAmazonDynamoDB,
    ArchitectureServiceAmazonRDS,
    ArchitectureServiceAmazonSimpleStorageService,
    ArchitectureServiceAmazonEFS,
    ArchitectureServiceAmazonVirtualPrivateCloud,
    ArchitectureServiceAmazonRoute53,
    ArchitectureServiceAmazonSimpleQueueService,
    ArchitectureServiceAmazonSimpleNotificationService,
    CategorySecurityIdentity,
    ArchitectureServiceAmazonCloudWatch,
    ArchitectureServiceAmazonElasticKubernetesService,
    ArchitectureServiceAmazonElasticContainerService,
    ArchitectureServiceAWSAmplify,
    ArchitectureServiceAmazonAPIGateway,
    ResourceElasticLoadBalancingApplicationLoadBalancer,
    ResourceAmazonVPCNATGateway,
    ResourceAmazonVPCInternetGateway,
    ArchitectureGroupPrivatesubnet,
    ArchitectureServiceAmazonCloudFront,
    ArchitectureServiceAmazonElastiCache,
    ArchitectureServiceAmazonKinesis,
    CategoryCompute,
    CategoryDatabases,
    CategoryStorage,
    CategoryNetworkingContentDelivery,
    ArchitectureServiceAWSGlue,
    ArchitectureServiceAWSStepFunctions,
    ArchitectureServiceAmazonEventBridge,
    ArchitectureServiceAmazonAthena,
    ArchitectureServiceAmazonEMR,
    ArchitectureServiceAWSDirectConnect,
    ArchitectureServiceAWSClientVPN,
    ArchitectureServiceAWSSitetoSiteVPN,
    ArchitectureServiceAmazonRedshift,
    ArchitectureServiceAmazonQuickSuite,
    ArchitectureServiceAmazonOpenSearchService,
    ArchitectureServiceAmazonManagedStreamingforApacheKafka,
    ArchitectureServiceAWSBatch,
    ArchitectureServiceAWSElasticBeanstalk,
    ArchitectureServiceAmazonElasticContainerRegistry,
    ArchitectureServiceAWSAppSync,
    ArchitectureServiceAmazonMQ,
    // AI & Machine Learning
    ArchitectureServiceAmazonBedrock,
    ArchitectureServiceAmazonSageMaker,
    ArchitectureServiceAmazonRekognition,
    ArchitectureServiceAmazonComprehend,
    ArchitectureServiceAmazonTextract,
    ArchitectureServiceAmazonTranslate,
    ArchitectureServiceAmazonTranscribe,
    ArchitectureServiceAmazonPolly,
    ArchitectureServiceAmazonLex,
    ArchitectureServiceAmazonPersonalize,
    ArchitectureServiceAmazonForecast,
    ArchitectureServiceAmazonKendra,
    CategoryArtificialIntelligence,
    // Developer Tools
    ArchitectureServiceAWSCodePipeline,
    ArchitectureServiceAWSCodeBuild,
    ArchitectureServiceAWSCodeDeploy,
    ArchitectureServiceAWSCodeCommit,
    ArchitectureServiceAWSCodeArtifact,
    ArchitectureServiceAWSCloud9,
    ArchitectureServiceAWSXRay,
    CategoryDeveloperTools,
    // Security
    ArchitectureServiceAmazonCognito,
    ArchitectureServiceAWSSecretsManager,
    ArchitectureServiceAmazonGuardDuty,
    ArchitectureServiceAmazonInspector,
    ArchitectureServiceAmazonMacie,
    ArchitectureServiceAWSSecurityHub,
    ArchitectureServiceAWSCertificateManager,
    ArchitectureServiceAWSCloudHSM,
    ArchitectureServiceAWSShield,
    ArchitectureServiceAWSKeyManagementService,
    ArchitectureServiceAWSWAF,
    // Database
    ArchitectureServiceAmazonNeptune,
    ArchitectureServiceAmazonDocumentDB,
    ArchitectureServiceAmazonTimestream,
    ArchitectureServiceAmazonKeyspaces,
    ArchitectureServiceAmazonMemoryDB,
    // Storage
    ArchitectureServiceAmazonFSx,
    ArchitectureServiceAWSBackup,
    ArchitectureServiceAWSStorageGateway,
    ArchitectureServiceAmazonSimpleStorageServiceGlacier,
    ArchitectureServiceAmazonElasticBlockStore,
    // Compute
    ArchitectureServiceAWSFargate,
    ArchitectureServiceAmazonLightsail,
    ArchitectureServiceAWSAppRunner,
    // Containers
    ArchitectureServiceAmazonEKSAnywhere,
    ArchitectureServiceAmazonECSAnywhere,
    CategoryContainers,
    // Management & Governance
    ArchitectureServiceAWSSystemsManager,
    ArchitectureServiceAWSConfig,
    ArchitectureServiceAWSCloudTrail,
    ArchitectureServiceAWSOrganizations,
    ArchitectureServiceAWSControlTower,
    ArchitectureServiceAWSServiceCatalog,
    ArchitectureServiceAWSTrustedAdvisor,
    ArchitectureServiceAWSCloudFormation,
    CategoryManagementTools,
    // Migration & Transfer
    ArchitectureServiceAWSDatabaseMigrationService,
    ArchitectureServiceAWSDataSync,
    ArchitectureServiceAWSTransferFamily,
    ArchitectureServiceAWSMigrationHub,
    ArchitectureServiceAWSTransitGateway,
    CategoryMigrationModernization,
    CategoryApplicationIntegration,
    CategoryAnalytics,
} from 'aws-react-icons';

export const getAwsIcon = (service: string, type: string): IconComponent => {
    const normalizedService = service?.toLowerCase().replace(/\s+/g, '') || '';
    const normalizedType = type?.toLowerCase() || '';

    const serviceMap: Record<string, React.ComponentType<any>> = {
        'ec2': ArchitectureServiceAmazonEC2,
        'lambda': ArchitectureServiceAWSLambda,
        's3': ArchitectureServiceAmazonSimpleStorageService,
        'dynamodb': ArchitectureServiceAmazonDynamoDB,
        'rds': ArchitectureServiceAmazonRDS,
        'vpc': ArchitectureServiceAmazonVirtualPrivateCloud,
        'sqs': ArchitectureServiceAmazonSimpleQueueService,
        'sns': ArchitectureServiceAmazonSimpleNotificationService,
        'iam': CategorySecurityIdentity,
        'cloudwatch': ArchitectureServiceAmazonCloudWatch,
        'eks': ArchitectureServiceAmazonElasticKubernetesService,
        'ecs': ArchitectureServiceAmazonElasticContainerService,
        'efs': ArchitectureServiceAmazonEFS,
        'route53': ArchitectureServiceAmazonRoute53,
        'amplify': ArchitectureServiceAWSAmplify,
        'apigateway': ArchitectureServiceAmazonAPIGateway,
        'directconnect': ArchitectureServiceAWSDirectConnect,
        'clientvpn': ArchitectureServiceAWSClientVPN,
        'sitetositevpn': ArchitectureServiceAWSSitetoSiteVPN,
        'vpn': ArchitectureServiceAWSClientVPN,
        'transitgateway': ArchitectureServiceAWSTransitGateway,
        'elb': ResourceElasticLoadBalancingApplicationLoadBalancer,
        'alb': ResourceElasticLoadBalancingApplicationLoadBalancer,
        'applicationloadbalancer': ResourceElasticLoadBalancingApplicationLoadBalancer,
        'natgateway': ResourceAmazonVPCNATGateway,
        'internetgateway': ResourceAmazonVPCInternetGateway,
        'privatesubnet': ArchitectureGroupPrivatesubnet,
        'elasticloadbalancing': ResourceElasticLoadBalancingApplicationLoadBalancer,
        'cloudfront': ArchitectureServiceAmazonCloudFront,
        'elasticache': ArchitectureServiceAmazonElastiCache,
        'kinesis': ArchitectureServiceAmazonKinesis,
        'glue': ArchitectureServiceAWSGlue,
        'stepfunctions': ArchitectureServiceAWSStepFunctions,
        'eventbridge': ArchitectureServiceAmazonEventBridge,
        'athena': ArchitectureServiceAmazonAthena,
        'emr': ArchitectureServiceAmazonEMR,
        'redshift': ArchitectureServiceAmazonRedshift,
        'quicksight': ArchitectureServiceAmazonQuickSuite,
        'opensearch': ArchitectureServiceAmazonOpenSearchService,
        'msk': ArchitectureServiceAmazonManagedStreamingforApacheKafka,
        'batch': ArchitectureServiceAWSBatch,
        'elasticbeanstalk': ArchitectureServiceAWSElasticBeanstalk,
        'ecr': ArchitectureServiceAmazonElasticContainerRegistry,
        'appsync': ArchitectureServiceAWSAppSync,
        'mq': ArchitectureServiceAmazonMQ,
        // AI & Machine Learning
        'bedrock': ArchitectureServiceAmazonBedrock,
        'sagemaker': ArchitectureServiceAmazonSageMaker,
        'rekognition': ArchitectureServiceAmazonRekognition,
        'comprehend': ArchitectureServiceAmazonComprehend,
        'textract': ArchitectureServiceAmazonTextract,
        'translate': ArchitectureServiceAmazonTranslate,
        'transcribe': ArchitectureServiceAmazonTranscribe,
        'polly': ArchitectureServiceAmazonPolly,
        'lex': ArchitectureServiceAmazonLex,
        'personalize': ArchitectureServiceAmazonPersonalize,
        'forecast': ArchitectureServiceAmazonForecast,
        'kendra': ArchitectureServiceAmazonKendra,
        // Developer Tools
        'codepipeline': ArchitectureServiceAWSCodePipeline,
        'codebuild': ArchitectureServiceAWSCodeBuild,
        'codecommit': ArchitectureServiceAWSCodeCommit,
        'codedeploy': ArchitectureServiceAWSCodeDeploy,
        'codeartifact': ArchitectureServiceAWSCodeArtifact,
        'cloud9': ArchitectureServiceAWSCloud9,
        'xray': ArchitectureServiceAWSXRay,
        'x-ray': ArchitectureServiceAWSXRay,
        // Security
        'cognito': ArchitectureServiceAmazonCognito,
        'secretsmanager': ArchitectureServiceAWSSecretsManager,
        'guardduty': ArchitectureServiceAmazonGuardDuty,
        'inspector': ArchitectureServiceAmazonInspector,
        'macie': ArchitectureServiceAmazonMacie,
        'securityhub': ArchitectureServiceAWSSecurityHub,
        'certificatemanager': ArchitectureServiceAWSCertificateManager,
        'acm': ArchitectureServiceAWSCertificateManager,
        'cloudhsm': ArchitectureServiceAWSCloudHSM,
        'shield': ArchitectureServiceAWSShield,
        'kms': ArchitectureServiceAWSKeyManagementService,
        'waf': ArchitectureServiceAWSWAF,
        // Database
        'neptune': ArchitectureServiceAmazonNeptune,
        'documentdb': ArchitectureServiceAmazonDocumentDB,
        'timestream': ArchitectureServiceAmazonTimestream,
        'keyspaces': ArchitectureServiceAmazonKeyspaces,
        'memorydb': ArchitectureServiceAmazonMemoryDB,
        'qldb': CategoryDatabases,
        // Storage
        'fsx': ArchitectureServiceAmazonFSx,
        'backup': ArchitectureServiceAWSBackup,
        'storagegateway': ArchitectureServiceAWSStorageGateway,
        's3-glacier': ArchitectureServiceAmazonSimpleStorageServiceGlacier,
        'glacier': ArchitectureServiceAmazonSimpleStorageServiceGlacier,
        'ebs': ArchitectureServiceAmazonElasticBlockStore,
        // Compute
        'fargate': ArchitectureServiceAWSFargate,
        'lightsail': ArchitectureServiceAmazonLightsail,
        'apprunner': ArchitectureServiceAWSAppRunner,
        // Containers
        'eksanywhere': ArchitectureServiceAmazonEKSAnywhere,
        'ecsanywhere': ArchitectureServiceAmazonECSAnywhere,
        // Management & Governance
        'systemsmanager': ArchitectureServiceAWSSystemsManager,
        'ssm': ArchitectureServiceAWSSystemsManager,
        'config': ArchitectureServiceAWSConfig,
        'cloudtrail': ArchitectureServiceAWSCloudTrail,
        'organizations': ArchitectureServiceAWSOrganizations,
        'controltower': ArchitectureServiceAWSControlTower,
        'servicecatalog': ArchitectureServiceAWSServiceCatalog,
        'trustedadvisor': ArchitectureServiceAWSTrustedAdvisor,
        'cloudformation': ArchitectureServiceAWSCloudFormation,
        // Migration & Transfer
        'dms': ArchitectureServiceAWSDatabaseMigrationService,
        'datasync': ArchitectureServiceAWSDataSync,
        'transferfamily': ArchitectureServiceAWSTransferFamily,
        'migrationhub': ArchitectureServiceAWSMigrationHub,
    };

    if (serviceMap[normalizedService]) {
        return serviceMap[normalizedService];
    }

    const typeMap: Record<string, React.ComponentType<any>> = {
        'aws-compute': CategoryCompute,
        'aws-database': CategoryDatabases,
        'aws-storage': CategoryStorage,
        'aws-network': CategoryNetworkingContentDelivery,
        'aws-ai': CategoryArtificialIntelligence,
        'aws-ml': CategoryArtificialIntelligence,
        'aws-devtools': CategoryDeveloperTools,
        'aws-security': CategorySecurityIdentity,
        'aws-containers': CategoryContainers,
        'aws-management': CategoryManagementTools,
        'aws-migration': CategoryMigrationModernization,
        'aws-integration': CategoryApplicationIntegration,
        'aws-analytics': CategoryAnalytics,
        'compute': CategoryCompute,
        'database': CategoryDatabases,
        'storage': CategoryStorage,
        'network': CategoryNetworkingContentDelivery,
        'ai': CategoryArtificialIntelligence,
        'ml': CategoryArtificialIntelligence,
        'devtools': CategoryDeveloperTools,
        'security': CategorySecurityIdentity,
        'containers': CategoryContainers,
        'management': CategoryManagementTools,
        'migration': CategoryMigrationModernization,
        'integration': CategoryApplicationIntegration,
        'analytics': CategoryAnalytics,
    };

    if (typeMap[normalizedType]) {
        return typeMap[normalizedType];
    }

    return Cpu;
};
